### ISSUE TITLE
Add MIT or other open license

### ISSUE THREAD

**Issue by rotemtam** [franklinlindemberg/go-samples#1]
Hi
Thanks for the great Kafka test containers example!

In order for this to be used in commercial settings copyrights need to be in order. Is there any chance you can publish this under MIT or similar license so it can be used?

**Comment by franklinlindemberg** [comment]
@rotemtam Sorry for the long delay to answer you. I have never received any notification about this issue.

I can definitely change that

**Comment by franklinlindemberg** [comment]
@rotemtam Just added it!

**Comment by rotemtam** [comment]
Thanks a lot!
